[2022-04-20 02:26:01,367] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_green_tripdata_partitioned_table_task scheduled__2022-04-19T00:00:00+00:00 [queued]>
[2022-04-20 02:26:01,373] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_green_tripdata_partitioned_table_task scheduled__2022-04-19T00:00:00+00:00 [queued]>
[2022-04-20 02:26:01,373] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-20 02:26:01,373] {taskinstance.py:1250} INFO - Starting attempt 3 of 3
[2022-04-20 02:26:01,373] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-20 02:26:01,380] {taskinstance.py:1270} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_green_tripdata_partitioned_table_task> on 2022-04-19 00:00:00+00:00
[2022-04-20 02:26:01,382] {standard_task_runner.py:52} INFO - Started process 5194 to run task
[2022-04-20 02:26:01,384] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'bq_create_green_tripdata_partitioned_table_task', 'scheduled__2022-04-19T00:00:00+00:00', '--job-id', '342', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_dag.py', '--cfg-path', '/tmp/tmprxlkzx2z', '--error-file', '/tmp/tmp7v2mp4l7']
[2022-04-20 02:26:01,384] {standard_task_runner.py:80} INFO - Job 342: Subtask bq_create_green_tripdata_partitioned_table_task
[2022-04-20 02:26:01,408] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_2_bq_dag.bq_create_green_tripdata_partitioned_table_task scheduled__2022-04-19T00:00:00+00:00 [running]> on host 5e56b5a44db8
[2022-04-20 02:26:01,429] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=bq_create_green_tripdata_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-04-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-19T00:00:00+00:00
[2022-04-20 02:26:01,430] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-20 02:26:01,430] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-04-20 02:26:01,435] {bigquery.py:1554} INFO - Inserting job ***_gcs_2_bq_dag_bq_create_green_tripdata_partitioned_table_task_2022_04_19T00_00_00_00_00_10b62e087490b27b5875a60cbfd1641b
[2022-04-20 02:26:02,923] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2153, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2119, in _submit_job
    retry=self.result_retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 439, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1560, in insert_job
    job.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1498, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1488, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: trips_data_all.green_tripdata_external_table, error message: Parquet column 'ehail_fee' has type DOUBLE which does not match the target cpp_type INT64.

Location: us-central1
Job ID: airflow_gcs_2_bq_dag_bq_create_green_tripdata_partitioned_table_task_2022_04_19T00_00_00_00_00_10b62e087490b27b5875a60cbfd1641b

[2022-04-20 02:26:02,930] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=gcs_2_bq_dag, task_id=bq_create_green_tripdata_partitioned_table_task, execution_date=20220419T000000, start_date=20220420T022601, end_date=20220420T022602
[2022-04-20 02:26:02,938] {standard_task_runner.py:98} ERROR - Failed to execute job 342 for task bq_create_green_tripdata_partitioned_table_task (400 Error while reading table: trips_data_all.green_tripdata_external_table, error message: Parquet column 'ehail_fee' has type DOUBLE which does not match the target cpp_type INT64.

Location: us-central1
Job ID: airflow_gcs_2_bq_dag_bq_create_green_tripdata_partitioned_table_task_2022_04_19T00_00_00_00_00_10b62e087490b27b5875a60cbfd1641b
; 5194)
[2022-04-20 02:26:02,959] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-20 02:26:02,974] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
