[2022-04-20 20:21:54,459] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_green_tripdata_partitioned_table_task scheduled__2022-04-19T00:00:00+00:00 [queued]>
[2022-04-20 20:21:54,464] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_green_tripdata_partitioned_table_task scheduled__2022-04-19T00:00:00+00:00 [queued]>
[2022-04-20 20:21:54,464] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-20 20:21:54,464] {taskinstance.py:1250} INFO - Starting attempt 8 of 9
[2022-04-20 20:21:54,465] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-20 20:21:54,471] {taskinstance.py:1270} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_green_tripdata_partitioned_table_task> on 2022-04-19 00:00:00+00:00
[2022-04-20 20:21:54,474] {standard_task_runner.py:52} INFO - Started process 3925 to run task
[2022-04-20 20:21:54,475] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'bq_create_green_tripdata_partitioned_table_task', 'scheduled__2022-04-19T00:00:00+00:00', '--job-id', '615', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_dag.py', '--cfg-path', '/tmp/tmppq1zq6kl', '--error-file', '/tmp/tmpu65y2ojw']
[2022-04-20 20:21:54,476] {standard_task_runner.py:80} INFO - Job 615: Subtask bq_create_green_tripdata_partitioned_table_task
[2022-04-20 20:21:54,500] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_2_bq_dag.bq_create_green_tripdata_partitioned_table_task scheduled__2022-04-19T00:00:00+00:00 [running]> on host 5a0aea9ec23a
[2022-04-20 20:21:54,522] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=bq_create_green_tripdata_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-04-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-19T00:00:00+00:00
[2022-04-20 20:21:54,523] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-20 20:21:54,523] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-04-20 20:21:54,528] {bigquery.py:1554} INFO - Inserting job ***_gcs_2_bq_dag_bq_create_green_tripdata_partitioned_table_task_2022_04_19T00_00_00_00_00_45f5a9363858ceb15a9ba4c4ab7bc4b2
[2022-04-20 20:21:56,265] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2153, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2119, in _submit_job
    retry=self.result_retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 439, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1560, in insert_job
    job.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1498, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1488, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: trips_data_all.green_tripdata_external_table, error message: Parquet column 'ehail_fee' has type DOUBLE which does not match the target cpp_type INT64.

Location: us-central1
Job ID: airflow_gcs_2_bq_dag_bq_create_green_tripdata_partitioned_table_task_2022_04_19T00_00_00_00_00_45f5a9363858ceb15a9ba4c4ab7bc4b2

[2022-04-20 20:21:56,273] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_2_bq_dag, task_id=bq_create_green_tripdata_partitioned_table_task, execution_date=20220419T000000, start_date=20220420T202154, end_date=20220420T202156
[2022-04-20 20:21:56,280] {standard_task_runner.py:98} ERROR - Failed to execute job 615 for task bq_create_green_tripdata_partitioned_table_task (400 Error while reading table: trips_data_all.green_tripdata_external_table, error message: Parquet column 'ehail_fee' has type DOUBLE which does not match the target cpp_type INT64.

Location: us-central1
Job ID: airflow_gcs_2_bq_dag_bq_create_green_tripdata_partitioned_table_task_2022_04_19T00_00_00_00_00_45f5a9363858ceb15a9ba4c4ab7bc4b2
; 3925)
[2022-04-20 20:21:56,292] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-20 20:21:56,307] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
